### ISSUE TITLE
Add Test Cases for 'Big Bang Integration Testing'

### ISSUE THREAD

**Issue by Chhavig28** [LoginRadius/awesome-test-cases-collection#23]
Add Test Cases for 'Big Bang Integration Testing'

**Comment by Ramona-Saintandre** [comment]
Hi @berry120


> Hey, I'd like to take this, please! If someone could link to what's meant by "big bang integration testing" that'd be awesome 👍

Here are some resources in regards to "Big Bang integration testing"

https://www.tutorialspoint.com/software_testing_dictionary/big_bang_testing.htm
https://www.guru99.com/integration-testing.html

**Comment by Chhavig28** [comment]
Closing issue.
