### ISSUE TITLE
Add Test Cases for 'API Fuzz Testing'

### ISSUE THREAD

**Issue by Chhavig28** [LoginRadius/awesome-test-cases-collection#27]
Add Test Cases for 'API Fuzz Testing'

**Comment by nirmalya8** [comment]
Hey @Chhavig28 , I am new to testing(do not have much knowledge) . I want to contribute to solve this issue. Can I get some guidance? Like Some examples of what should I add or some resources. As far as I know, API testing involves checking the result of the API at unexpected values(like edge cases)

**Comment by Chhavig28** [comment]
Closing issue.
