### ISSUE TITLE
Add Test Cases for 'Riskbased Authentication Testing'

### ISSUE THREAD

**Issue by Chhavig28** [LoginRadius/awesome-test-cases-collection#30]
Add Test Cases for 'Riskbased Authentication Testing'

**Comment by Ln11211** [comment]
@Chhavig28, can you please assign this to me ?

**Comment by Ln11211** [comment]
I want to work on this

**Comment by kambojshalabh35** [comment]
Hey @Chhavig28 please review PR #50

**Comment by kambojshalabh35** [comment]
Hey @Chhavig28 please review PR #50
